PYTHON := .venv/bin/python

.DEFAULT_GOAL := help

# ── Parameters (append as VAR=value) ──────────────────────────────────────────
ARGS ?=                        # passthrough flags (lint / run)

# ── Help ──────────────────────────────────────────────────────────────────────
.PHONY: help
help:
	@echo ""
	@echo "  SecurityAnalysisAgents  —  make <target> [VAR=value ...]"
	@echo ""
	@echo "  Setup & run"
	@echo "    setup                Create .venv (python3), install the package, scaffold .env"
	@echo "    setup-locked         Same, from pinned requirements.lock (reproducible env)"
	@echo "    install-dev          Install package + dev tooling (ruff, pytest)"
	@echo "    run                  Launch the interactive CLI"
	@echo "    demo                 Run the scripted sample analysis (main.py) — uses real, paid LLM calls"
	@echo ""
	@echo "  Docker"
	@echo "    docker-build         Build the container image"
	@echo "    docker-run           Run the CLI in a container (reads .env)"
	@echo "    docker-ollama        Run against a bundled Ollama container (local models)"
	@echo ""
	@echo "  Developer"
	@echo "    test                 Run the test suite"
	@echo "    lint                 Lint with ruff (ARGS=--fix to auto-fix)"
	@echo "    lock                 Regenerate requirements.lock from the current .venv"
	@echo "    clean                Remove .venv, caches, and build artifacts"
	@echo ""
	@echo "  First run:  make setup  ->  edit .env (add an API key)  ->  make run"
	@echo ""

# ── Setup & run ───────────────────────────────────────────────────────────────
.PHONY: setup setup-locked install-dev run demo _post-setup
setup:
	python3 -m venv .venv
	$(PYTHON) -m pip install --upgrade pip
	$(PYTHON) -m pip install -e .          # editable install: deps + package on sys.path
	@$(MAKE) --no-print-directory _post-setup

# Reproducible install: exact pinned versions from requirements.lock. Regenerate
# the lock after changing deps with `make lock`. `make setup` resolves fresh from
# the loose pyproject spec instead.
setup-locked:
	python3 -m venv .venv
	$(PYTHON) -m pip install --upgrade pip
	$(PYTHON) -m pip install -r requirements.lock
	$(PYTHON) -m pip install -e . --no-deps
	@$(MAKE) --no-print-directory _post-setup

install-dev:
	$(PYTHON) -m pip install -e ".[dev]"

_post-setup:
	@cp -n .env.example .env 2>/dev/null || true
	@echo ""
	@echo "  Setup complete. Next:"
	@echo "    1. Edit .env          (add at least one provider API key)"
	@echo "    2. make run           (or: make demo for the scripted sample)"
	@echo ""

run:
	$(PYTHON) -m cli.main $(ARGS)

# Scripted sample (NVDA). This makes real LLM calls and can incur cost — set your
# provider key in .env first.
demo:
	$(PYTHON) main.py

# ── Docker ────────────────────────────────────────────────────────────────────
.PHONY: docker-build docker-run docker-ollama
docker-build:
	docker compose build

docker-run:
	docker compose run --rm securityanalysisagents

docker-ollama:
	docker compose --profile ollama run --rm securityanalysisagents-ollama

# ── Developer ─────────────────────────────────────────────────────────────────
.PHONY: test lint lock clean
test:
	$(PYTHON) -m pytest $(ARGS)

lint:
	$(PYTHON) -m ruff check . $(ARGS)

# Pin the currently-resolved environment. --exclude-editable drops the editable
# self-install (securityanalysisagents) so the lock holds only third-party deps. The lock
# is platform/Python-specific (regenerated on the maintainer's macOS + py3.12);
# it backs `make setup-locked`, while `make setup` stays the portable default.
lock:
	@printf '%s\n' \
		'# Pinned, reproducible dependency set for `make setup-locked`.' \
		'# Generated by `make lock` on the maintainer'\''s env (macOS, Python 3.12).' \
		'# Platform/Python-specific — a reproducibility aid, not a universal constraint.' \
		'# `make setup` resolves fresh from pyproject.toml and is the portable default.' \
		> requirements.lock
	$(PYTHON) -m pip freeze --exclude-editable >> requirements.lock
	@echo "Wrote requirements.lock"

clean:
	rm -rf .venv build dist *.egg-info .pytest_cache .ruff_cache
	find . -type d -name __pycache__ -prune -exec rm -rf {} +
